import { format } from 'date-fns';
import { Button } from '@/components/ui/button';
import { FileDown } from 'lucide-react';

interface InvoiceData {
  transactionId: string;
  amount: number;
  paymentMethod: string;
  paymentDate: string;
  paymentStatus: string;
  billType: string;
  billDescription?: string;
  billDueDate?: string;
  userName?: string;
  userEmail?: string;
}

function generateInvoiceHTML(data: InvoiceData): string {
  return `
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: 'Segoe UI', sans-serif; margin: 0; padding: 40px; background: #f8fafc; }
  .invoice { max-width: 600px; margin: 0 auto; background: white; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.08); }
  .header { background: linear-gradient(135deg, #4f46e5, #7c3aed); padding: 32px; color: white; }
  .header h1 { margin: 0; font-size: 28px; font-weight: 800; }
  .header p { margin: 4px 0 0; opacity: 0.8; font-size: 14px; }
  .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 700; text-transform: uppercase; }
  .badge-success { background: rgba(34,197,94,0.2); color: #16a34a; }
  .badge-failed { background: rgba(239,68,68,0.2); color: #dc2626; }
  .content { padding: 32px; }
  .section { margin-bottom: 24px; }
  .section-title { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: #94a3b8; margin-bottom: 12px; }
  .row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #f1f5f9; }
  .row:last-child { border-bottom: none; }
  .label { color: #64748b; font-size: 14px; }
  .value { font-weight: 600; font-size: 14px; color: #1e293b; }
  .amount-row .value { font-size: 24px; font-weight: 800; color: #4f46e5; }
  .footer { text-align: center; padding: 20px; border-top: 1px solid #f1f5f9; color: #94a3b8; font-size: 12px; }
  .status-bar { display: flex; align-items: center; gap: 8px; padding: 12px 16px; border-radius: 12px; margin-bottom: 20px; }
  .status-bar.success { background: #f0fdf4; }
  .status-bar.failed { background: #fef2f2; }
</style>
</head>
<body>
<div class="invoice">
  <div class="header">
    <div style="display: flex; justify-content: space-between; align-items: center;">
      <div>
        <h1>⚡ BillStack</h1>
        <p>Payment Invoice</p>
      </div>
      <span class="badge ${data.paymentStatus === 'SUCCESS' ? 'badge-success' : 'badge-failed'}">
        ${data.paymentStatus}
      </span>
    </div>
  </div>
  <div class="content">
    <div class="status-bar ${data.paymentStatus === 'SUCCESS' ? 'success' : 'failed'}">
      <span style="font-size: 18px;">${data.paymentStatus === 'SUCCESS' ? '✅' : '❌'}</span>
      <span style="font-weight: 600; font-size: 14px; color: ${data.paymentStatus === 'SUCCESS' ? '#16a34a' : '#dc2626'};">
        Payment ${data.paymentStatus === 'SUCCESS' ? 'Completed Successfully' : 'Failed'}
      </span>
    </div>

    <div class="section">
      <div class="section-title">Transaction Details</div>
      <div class="row">
        <span class="label">Transaction ID</span>
        <span class="value" style="font-family: monospace; font-size: 12px;">${data.transactionId}</span>
      </div>
      <div class="row">
        <span class="label">Date & Time</span>
        <span class="value">${format(new Date(data.paymentDate), 'MMM d, yyyy HH:mm:ss')}</span>
      </div>
      <div class="row">
        <span class="label">Payment Method</span>
        <span class="value">${data.paymentMethod.replace('_', ' ')}</span>
      </div>
    </div>

    <div class="section">
      <div class="section-title">Bill Information</div>
      <div class="row">
        <span class="label">Bill Type</span>
        <span class="value">${data.billType}</span>
      </div>
      ${data.billDescription ? `<div class="row"><span class="label">Description</span><span class="value">${data.billDescription}</span></div>` : ''}
      ${data.billDueDate ? `<div class="row"><span class="label">Due Date</span><span class="value">${format(new Date(data.billDueDate), 'MMM d, yyyy')}</span></div>` : ''}
    </div>

    <div class="section">
      <div class="section-title">Payment Summary</div>
      <div class="row amount-row">
        <span class="label" style="font-size: 16px;">Total Paid</span>
        <span class="value">$${data.amount.toFixed(2)}</span>
      </div>
    </div>

    ${data.userName || data.userEmail ? `
    <div class="section">
      <div class="section-title">Billed To</div>
      ${data.userName ? `<div class="row"><span class="label">Name</span><span class="value">${data.userName}</span></div>` : ''}
      ${data.userEmail ? `<div class="row"><span class="label">Email</span><span class="value">${data.userEmail}</span></div>` : ''}
    </div>` : ''}
  </div>
  <div class="footer">
    <p>Generated by BillStack • ${format(new Date(), 'MMM d, yyyy HH:mm')}</p>
    <p>This is a computer-generated invoice. No signature required.</p>
  </div>
</div>
</body>
</html>`;
}

export function downloadInvoice(data: InvoiceData) {
  const html = generateInvoiceHTML(data);
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  }
}

export default function InvoiceDownloadButton({ payment, bill, profile }: {
  payment: any;
  bill?: any;
  profile?: { name?: string; email?: string };
}) {
  const handleDownload = () => {
    downloadInvoice({
      transactionId: payment.transaction_id,
      amount: Number(payment.amount),
      paymentMethod: payment.payment_method,
      paymentDate: payment.payment_date,
      paymentStatus: payment.payment_status,
      billType: bill?.bill_type || (payment as any).bills?.bill_type || 'N/A',
      billDescription: bill?.description || (payment as any).bills?.description,
      billDueDate: bill?.due_date || (payment as any).bills?.due_date,
      userName: profile?.name,
      userEmail: profile?.email,
    });
  };

  return (
    <Button variant="outline" size="sm" onClick={handleDownload} className="gap-2">
      <FileDown className="h-4 w-4" />
      Invoice
    </Button>
  );
}
